# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "6d000a85f99924fe7c3f6be566cb2283"
name = "cartrecovery-ai"
application_url = "https://app.dropsify.shop"
embedded = true

[build]
automatically_update_urls_on_dev = true

[webhooks]
api_version = "2026-04"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://app.dropsify.shop/webhooks/customers/redact"
  customer_data_request_url = "https://app.dropsify.shop/webhooks/customers/data_request"
  shop_deletion_url = "https://app.dropsify.shop/webhooks/shop/redact"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

  [[webhooks.subscriptions]]
  topics = [ "app/scopes_update" ]
  uri = "/webhooks/app/scopes_update"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [ "https://app.dropsify.shop/auth/callback", "https://app.dropsify.shop/auth/shopify/callback", "https://app.dropsify.shop/api/auth/callback" ]
